FROM itzg/minecraft-server:java21

# Install manual downloads that can't be  automatically
# downloaded on provision
COPY custom/prominence-2-rpg/Luna-FABRIC-MC1.19.X-1.0.1.jar /downloads/Luna-FABRIC-MC1.19.X-1.0.1.jar
