version: 2.1

orbs:
  docker: circleci/docker@2.8.1

workflows:
  build_custom_images:
    jobs:
      - docker/publish:
          context: DockerHub
          image: cwagne17/prominence-2-rpg
          path: custom/prominence-2-rpg
          tag: latest
